### ISSUE TITLE
Add Hacktoberfest banner

### ISSUE THREAD

**Issue by OleksiyRudenko** [kottans/hacktoberfest#5]
... at the top of `README.md` yet below badges

Image options:
- [730x90](https://drive.google.com/open?id=1zNximyhMAYRJkRWgl2V6Pmhvcud9UU5r)
- [620x76](https://drive.google.com/open?id=127G7pW_3g86PTcQyaA4Qe-e_qzZxrKZc)

The image should fit `README.md` view width on GitHub

**Comment by OleksiyRudenko** [comment]
@AMashoshyna I would lovely add the banner to `README.md`. Can I?

**Comment by AMashoshyna** [comment]
@OleksiyRudenko sure, thank you!

**Comment by OleksiyRudenko** [comment]
@AMashoshyna I am terribly sorry but I have to leave the city and won't be able to complete the task. Please unassign.

For the record: this assignment has been done for demo purposes.

**Comment by Zihfred** [comment]
I can get this task

**Comment by OleksiyRudenko** [comment]
@Zihfred thank you for your proposal. It's all yours.

Please take an effort to check how it would look on various devices including mobile. Thank you
